apiVersion: v1
kind: Service

metadata:
  name: custom-html-service

spec:
  selector:
    app: custom-html-app

  type: NodePort

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002